fixed bug:  SolidityFileName.sol:ContractName now shown in files
Certora/vscode-certora-prover pull request #60
Opened 2022-04-18 13:43 UTC by NoaBablikiCertora

Here I'm suggesting a solution to the bug: 

> Configuration file does not include the contract name

in the configuration file.

2022-04-18 13:45 UTC, NoaBablikiCertora commented
I made a previous pull request for the same fix, but on a brach with my other changed and it was messy so I closed the other request and open this one.
Sorry about the mess, I'm still learning how to do this.

2022-04-25 06:55 UTC, fnast9 requested changes
Noa, you fixed it correctly :+1: 
However, we can make it even better (and it won't require too much time).

2022-04-25 06:55 UTC, fnast9 commented on src/extension/utils/createAndOpenConfFile.ts
> +      `${inputFormData.mainSolidityFile}:${inputFormData.mainContractName}`,
You did it the right way. But let's take it a step forward.
You probably noticed that currently, there is no inputs validation. However, we may start adding it.
So, I would recommend you do the following:
- See what happens if the `mainContractName` is `null` (or empty).
- By the way, if it's missing, it's doesn't make it wrong. If Solidity filename is  `{CONTRACT_NAME}.sol`, the run command can be `certoraRun {CONTRACT_NAME}.sol --verify {CONTRACT_NAME}:{SPEC_FILE}`.

2022-04-27 11:13 UTC, fnast9 commented on src/extension/utils/createAndOpenConfFile.ts
> +      inputFormData.mainContractName.length > 0
An empty string evaluates to false

2022-04-27 12:25 UTC, fnast9 approved these changes

2022-04-27 12:33 UTC, merged