UI fixes and PROBLEMS view
Certora/vscode-certora-prover pull request #87
Opened 2023-01-29 12:47 UTC by NoaBablikiCertora

2023-01-29 14:17 UTC, NoaBablikiCertora commented
* remove hover from the information icon

* remove default values from duration / loop_iter

* add an option to choose branch in production: customize branch, staging

2023-03-07 11:05 UTC, Biced requested changes
almost corgi keshet

2023-03-07 11:05 UTC, Biced commented on src/results/App.svelte
>     * run all the runs that are allowed to run
please rewrite using filter

2023-03-07 11:05 UTC, Biced commented on src/results/App.svelte
> +                // $verificationResults = $verificationResults.filter(vr => {
please delete comments

2023-03-07 11:05 UTC, Biced commented on src/results/App.svelte
> +          <!-- {/key} -->
delete comment

2023-03-19 09:14 UTC, merged