Sh to job feature
Certora/vscode-certora-prover pull request #88
Opened 2023-02-16 15:16 UTC by NoaBablikiCertora

create jobs from shell scripts:
- initially, all the scripts in the certora/script directory will become jobs
- while working, every shell script file that is copyed into the script directory will become a job

2023-03-06 07:43 UTC, NoaBablikiCertora commented
1. choose a shell script file from the browser
2. if the script is a legal certora cli shell script, it will become a new job. otherwise, there will be a popup describing the problem with the script

2023-03-12 11:06 UTC, sarittenen commented on CHANGELOG.md
> +* Added option to choose branch in production ([#87](https://github.com/Certora/vscode-certora-prover/pull/87))
choose branch on production/ staging

2023-03-12 11:06 UTC, sarittenen commented on CHANGELOG.md
> +* Change icon in navigator when there is a validation error ([#87](https://github.com/Certora/vscode-certora-prover/pull/87))
+ settings error icon
+error handling

2023-03-12 14:07 UTC, Biced requested changes

2023-03-12 14:07 UTC, Biced commented on src/settings/SolSettingsTab.svelte
> +  class={'card_parent_wrapper bg_dark border-rd ' +
<div
  class='card_parent_wrapper bg_dark border-rd'
    class:disable_main="{$disableForm }"
>

2023-03-12 14:42 UTC, NoaBablikiCertora commented on src/extension/utils/getRunInternalInfo.ts
> +      if (dir[1] === 2) {
added explicit typing to "dir" in "getInternalDirPath"

2023-03-19 09:22 UTC, merged