save last run results
Certora/vscode-certora-prover pull request #92
Opened 2023-03-20 14:21 UTC by NoaBablikiCertora

save last run results and present them

2023-03-28 16:47 UTC, Biced requested changes
almost Corgi keshet

2023-03-28 16:47 UTC, Biced commented on src/results/components/NewRun.svelte
> +  // import { onDestroy, onMount } from 'svelte'
comment

2023-03-29 08:07 UTC, NoaBablikiCertora commented on src/extension/extension.ts
> +        // can't delete results file
I'm not sure it is something the user has anything to do with. this is an inner file I create / delete if it is not there for some reason the user shouldn't care

2023-03-29 08:08 UTC, NoaBablikiCertora commented on src/extension/extension.ts
> +      .then(async items => {
"clear results" is asynchronous because it deletes a file

2023-03-29 16:08 UTC, Biced commented on src/extension/ScriptRunner.ts
> +        data: JSON.parse(JSON.stringify(data)),
data: {...data}

2023-03-29 16:11 UTC, Biced commented on src/extension/extension.ts
> +        // can't delete results file
then what is the point of the try catch if no one knows there is an error?
just to avoid breaking the code

2023-03-30 08:19 UTC, NoaBablikiCertora commented on src/extension/extension.ts
> +        // can't delete results file
yes

2023-03-30 08:21 UTC, NoaBablikiCertora commented on src/extension/ScriptRunner.ts
> +        data: JSON.parse(JSON.stringify(data)),
deep copy

2023-03-30 09:59 UTC, Biced approved these changes
Corgi keshet

2023-04-02 10:50 UTC, merged