Better translation code
Certora/vscode-certora-prover pull request #94
Opened 2023-03-22 13:14 UTC by NoaBablikiCertora

translation from form format to conf file format was very ugly
This is a nicer looking solution

2023-03-28 20:41 UTC, Biced requested changes
a lot of this JSON.stringify(config, null, 2) any reason you need the extra indentation? 
a lot of string/array.reverse()[0] - I don't like this approach in general.
in this PR it really shows that it is bad practice since you have to reverse it back again.

2023-03-28 20:41 UTC, Biced commented on src/extension/utils/createConfFile.ts
> +    if (rulesArr.length > 0) {
rulesArr.length

2023-03-28 20:41 UTC, Biced commented on src/extension/utils/confFileToFormData.ts
> +  if (Object.keys(additionalSettings)?.length > 0) {
Object.keys(additionalSettings)?.length

2023-03-28 20:41 UTC, Biced commented on src/extension/utils/confFileToFormData.ts
> +  if (Array.isArray(confFile.files) && confFile.files.length > 0) {
confFile.files.length

2023-03-28 20:41 UTC, Biced commented on src/extension/utils/confFileToFormData.ts
> +  if (confFile.files && confFile.files.length > 1) {
confFile.files?.length

2023-03-28 20:41 UTC, Biced commented on src/extension/utils/confFileToFormData.ts
> +    ? fileStr.split(':').reverse()[0]
please avoid using reverse() to get the last member of an array

2023-03-28 20:41 UTC, Biced commented on src/extension/utils/confFileToFormData.ts
> +      if (confFile.link && confFile.link.length > 0) {
confFile.link?.length

2023-03-28 20:41 UTC, Biced commented on src/extension/utils/confFileToFormData.ts
> +      }
else if (confFile.solc?.includes('/')) {
          const solcArr = confFile.solc.split('/')
          tempForm.compiler.ver = solcArr.pop() || ''
          tempForm.compiler.exe = solcArr.reverse().join('/')
        } else {
          tempForm.compiler.ver = confFile.solc
      }

      tempForm.compiler.exe = solcArr.reverse().join('/') - this is why reverse() is so bad to get the last member in a string/array

2023-03-29 14:04 UTC, NoaBablikiCertora commented on src/settings/utils/confFileToFormData.ts
> +  if (confFile.files && confFile.files.length > 1) {
>1 not 0

2023-03-29 16:05 UTC, Biced commented on src/extension/utils/confFileToFormData.ts
> +  if (confFile.files && confFile.files.length > 1) {
confFile.files?.length > 1
didn't notice the 1

2023-04-02 08:02 UTC, Biced requested changes
Corgi keshet, just remove the comment

2023-04-02 09:27 UTC, Biced requested changes

2023-04-02 09:30 UTC, Biced approved these changes
Corgi keshet

2023-04-02 12:44 UTC, merged